// Web-ready venue photo derivatives (generated by
// scripts/process-venue-images.mjs from the originals under
// public/images/events/venue — originals are never modified).
//
// Alt text describes the space and what is happening; it is part of the
// photo-selection review, so keep edits factual. The venue has one
// full-coverage roll-out floor mat and 15 feet of rollaway mirrors; never
// describe sprung floors or individual mats.

export interface VenueImage {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const venueImages = {
  mainHallRoseWindow: { src: '/images/pages/venue/main-hall-rose-window.webp', alt: "The main hall of the restored 1905 church, with a rose window and five arched stained-glass windows above a polished wood floor", width: 1800, height: 2400 },
  sunlitHall: { src: '/images/pages/venue/sunlit-hall.webp', alt: "Sunlight warms the wood floor of the vaulted main hall, looking toward the shoji-screen partition and antique pews", width: 1800, height: 2400 },
  exteriorFront: { src: '/images/pages/venue/exterior-front.webp', alt: "Front view of the restored 1905 brick church and its adjoining workspace building under a dramatic sky", width: 2048, height: 1142 },
  cafeLounge: { src: '/images/pages/venue/cafe-lounge.webp', alt: "The lounge area with cafe tables, counter seating, and a carved wooden pew beneath stained-glass windows", width: 1600, height: 1200 },
  seatedSemicircle: { src: '/images/pages/venue/seated-semicircle.webp', alt: "Rows of chairs arranged in a semicircle across the wood floor of the vaulted event hall", width: 1600, height: 1500 },
  exteriorSummer: { src: '/images/pages/venue/exterior-summer.webp', alt: "The historic brick church seen from the tree-lined sidewalk on a sunny summer day", width: 1600, height: 1200 },
  sunlitHallPartition: { src: '/images/pages/venue/sunlit-hall-partition.webp', alt: "Sunlight streaks the long wood floor of the empty hall, facing the wood-framed partition wall and arched windows", width: 1800, height: 2400 },
  fullCoverageMat: { src: '/images/pages/venue/full-coverage-mat.webp', alt: "The hall's single full-coverage roll-out floor mat spans the room wall to wall beneath arched stained-glass windows", width: 2400, height: 1791 },
  hallProjectionScreen: { src: '/images/pages/venue/hall-projection-screen.webp', alt: "The empty hall with polished wood floors, arched stained-glass windows, and a projection screen beneath the rose window", width: 1200, height: 1600 },
  // Landscape hero crops of the portrait originals, so wide hero sections
  // show the architecture instead of a zoomed mid-band.
  mainHallRoseWindowWide: { src: '/images/pages/venue/main-hall-rose-window-wide.webp', alt: "The main hall of the restored 1905 church, with a rose window and four arched stained-glass windows above a polished wood floor", width: 2400, height: 1360 },
  sunlitHallWide: { src: '/images/pages/venue/sunlit-hall-wide.webp', alt: "Sunlight warms the wood floor of the vaulted main hall, looking toward the shoji-screen partition and antique pews", width: 2400, height: 1480 },
  sunlitHallPartitionWide: { src: '/images/pages/venue/sunlit-hall-partition-wide.webp', alt: "Sunlight streaks the long wood floor of the empty hall, facing the wood-framed partition wall and arched windows", width: 2400, height: 1480 },
} as const;

export const weddingsImages = {
  celebrationKiss: { src: '/images/pages/weddings/celebration-kiss.webp', alt: "A wedding party cheers as the couple kisses before the grand stained-glass window of the church hall", width: 1080, height: 649 },
  aisleRecessional: { src: '/images/pages/weddings/aisle-recessional.webp', alt: "Newlyweds walk back down the aisle to applause beneath the church's stained-glass windows", width: 1080, height: 707 },
  cakeTableCouple: { src: '/images/pages/weddings/cake-table-couple.webp', alt: "A bride and groom share a look over their wedding cake beneath a draped floral arch in the reception hall", width: 1143, height: 1600 },
  headTableCake: { src: '/images/pages/weddings/head-table-cake.webp', alt: "A decorated head table with a tiered wedding cake set against the hall's wooden partition and stained glass", width: 900, height: 1600 },
  gettingReady: { src: '/images/pages/weddings/getting-ready.webp', alt: "A bride laughs with her attendants while getting ready in the venue's stone-walled suite", width: 1010, height: 1093 },
} as const;

export const concertsImages = {
  songwritersRound: { src: '/images/pages/concerts/songwriters-round.webp', alt: "Four musicians perform a songwriters' round beneath the rose window as an audience looks on", width: 2400, height: 1800 },
  danceFloorCrowd: { src: '/images/pages/concerts/dance-floor-crowd.webp', alt: "A crowd dances on the wood floor of the church hall beneath its arched windows during an evening event", width: 1200, height: 1600 },
  acousticAudience: { src: '/images/pages/concerts/acoustic-audience.webp', alt: "An audience watches an acoustic performance beneath the stained-glass rose window of the historic hall", width: 1600, height: 1412 },
  tangoStarryCeiling: { src: '/images/pages/concerts/tango-starry-ceiling.webp', alt: "Couples dance tango beneath a starry projected ceiling, the hall's tall arched window glowing behind them", width: 1600, height: 1200 },
} as const;

export const artShowsImages = {
  exhibitionStainedGlass: { src: '/images/pages/art-shows/exhibition-stained-glass.webp', alt: "Sunlit hall with artwork displayed along the partition wall and three arched stained-glass windows lighting the wood floor", width: 1920, height: 1440 },
  vaultedHallExhibition: { src: '/images/pages/art-shows/vaulted-hall-exhibition.webp', alt: "Wide view of the vaulted hall during an art exhibition, with paintings on the white brick and partition walls and stained-glass windows at right", width: 1600, height: 1200 },
  artShowTables: { src: '/images/pages/art-shows/art-show-tables.webp', alt: "Framed artwork displayed on round tables across the hall's wood floor during a community art show", width: 1600, height: 1200 },
  visitorsBrowsing: { src: '/images/pages/art-shows/visitors-browsing.webp', alt: "Visitors browse framed artwork on easels and round tables during an art show beneath the hall's arched stained-glass windows", width: 1170, height: 862 },
  partitionWallPaintings: { src: '/images/pages/art-shows/partition-wall-paintings.webp', alt: "Abstract paintings hang on the wood-and-glass partition wall of the hall, with benches and small wooden tables arranged below", width: 1600, height: 1200 },
  paintingsOverPews: { src: '/images/pages/art-shows/paintings-over-pews.webp', alt: "Framed abstract works on the partition wall above a row of antique wooden pews, stained glass glowing through the panels", width: 1600, height: 1200 },
} as const;

export const classesImages = {
  danceClassStringLights: { src: '/images/pages/classes/dance-class-string-lights.webp', alt: "A dance class moves in step across the wood floor of the hall under strings of warm lights", width: 2400, height: 1603 },
  danceClassSteps: { src: '/images/pages/classes/dance-class-steps.webp', alt: "Dancers practice steps together during a class in the wood-beamed hall", width: 1600, height: 1069 },
  breathworkClass: { src: '/images/pages/classes/breathwork-class.webp', alt: "A breathwork class practices seated arm movements together on the hall's wood floor", width: 1600, height: 1067 },
  martialArtsPractice: { src: '/images/pages/classes/martial-arts-practice.webp', alt: "An instructor coaches two young students practicing grappling on the full-coverage floor mat", width: 1225, height: 1600 },
  circleRollawayMirror: { src: '/images/pages/classes/circle-rollaway-mirror.webp', alt: "Class members sit in a circle on the wood floor for a discussion, reflected in the studio's rollaway mirror", width: 1600, height: 1069 },
  restorativeClass: { src: '/images/pages/classes/restorative-class.webp', alt: "A large restorative class rests on the wood floor of the hall, lit by tall blue stained-glass windows", width: 1600, height: 1032 },
  soundBathCandlelight: { src: '/images/pages/classes/sound-bath-candlelight.webp', alt: "Candlelit sound bath setup with a gong, singing bowls, and mats beneath an aurora projection on the vaulted ceiling", width: 810, height: 1080 },
  soundBathRoseWindow: { src: '/images/pages/classes/sound-bath-rose-window.webp', alt: "Singing bowls and candles glow beneath the stained-glass rose window during an evening sound bath", width: 810, height: 1080 },
  soundBathGathering: { src: '/images/pages/classes/sound-bath-gathering.webp', alt: "Participants gather among mats and candles under a projected purple sky during a sound bath event", width: 960, height: 1280 },
} as const;

export const congregationsImages = {
  communityCircle: { src: '/images/pages/congregations/community-circle.webp', alt: "A community congregation gathers in a circle of chairs for a discussion in the church hall", width: 1600, height: 1200 },
  sundayService: { src: '/images/pages/congregations/sunday-service.webp', alt: "Pastor Tate preaches beside an interpreter during a bilingual Sunday service in the hall", width: 1130, height: 900 },
} as const;

