// Auto-generated blur placeholders for images
// Run: node scripts/generate-blur-placeholders.js

export const blurDataMap: Record<string, string> = {
  "/images/event-banners/Boy-Mom.png": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAYABUB8JQBOgB87NOQAAP637JO2sryKJcRqepjSa4E2r5uPvDPaxLfzgAAA",
  "/images/event-banners/Cayla-Headshot.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoIAAoABUB8JZgCdAEekgiSowAA8f0CVr5iyxsOUuxqNbemu0ll532Sn0XGBho1CluAJAAA",
  "/images/event-banners/Channel One Sound System June 7, 2026.png": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAQCdASoIAAoABUB8JZgCdAFAAAD+7WeNjS1u9j8RvlzKNfzrcqpxzabY5SAn7P44AA==",
  "/images/event-banners/Event.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAoABUB8JaACdAEfaSyoAAD+va7rp6770DxQTAlrv+rJ/HHg5kvWiyKDLbZ5AAA=",
  "/images/event-banners/Foundations of a Healthy Back Banner image.jpg": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoKAAYABUB8JZwAAucH8zgAAP7JQUexxajQSqsIWJviL9MAAAA=",
  "/images/event-banners/Julie_headshot2.jpeg": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAoABUB8JQBOgB8w56tjYADwC3ON+DUd0CF09JO+PpmBy2PqOjrkgzxV6ct4HEpIAA==",
  "/images/event-banners/June.png": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAMABUB8JZACdADdGF3sAP6+g/R7QdfnzvKRVXWRCfuJauXE7pwQ3QAAAA==",
  "/images/event-banners/MHQ.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAoABUB8JbACdADyUhuAAOjwCdeZWoMATQN1MJgFw8FJuO0trt5HYfIN1kaWAAA=",
  "/images/event-banners/May 21 Yin Massage Sound Bath.jpg": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JQBdgCHZht/8AAD+5+3HFCVki/WNYAf4ACkY1n1tAAAA",
  "/images/event-banners/Slow Flow + Nervous Syetem Reset.JPEG": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoIAAoABUB8JQAAXU5r1WLAAAD+1exgxN9HfSqNUHiGqN/GaMLLob90nNxb6wDefRAmeSNd8+AAAA==",
  "/images/event-banners/Sound Immersion Event Header 2026.png": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAYABUB8JQBOgBtH9wygAP7T5hgmkC7irI3h9WoO00wTyX4/7AAA",
  "/images/event-banners/Terri-Event.JPG": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoHAAoABUB8JYgC7AEOZk4JygAA4Bk0axIXlGZUB7qiN13QwN0R8WvNCvxfgAAA",
  "/images/event-banners/Western-Wish-April.png": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoIAAoABUB8JYgAAuZttgAA/sdpR2XK7XCBoIg9HrI5h7WLS30JatsRSGx58eFLsAA=",
  "/images/event-banners/Western-Wish.png": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAoABUB8JaQAAu1geicgAP7qo45uDqQBbABDmkS8hVLhruOHrSAAAAA=",
  "/images/event-banners/breathwork.webp": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoIAAoABUB8JYwAAuYa/9bYAPKPyEGfS5U4Do05wPGIcUAA",
  "/images/event-banners/gala.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JYwCdAELXTlCkAD+6fKAMnzI/wsAkvLAvgBSx0HEfYgA",
  "/images/event-banners/kids.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoJAAoABUB8JbACdADZYwDkAAD+x2+BAMIFKR23bfjwvq5XZXeHfaHAJQDLuxwdgu20C/Uj1W4FEAAA",
  "/images/event-banners/tantra.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoKAAoABUB8JbACdADZYq0AAOAmvMl9xgW97aDFfXXmu53EnC+SxoEuIacbaDiIqzBwWXOEoBapw5sAAAA=",
  "/images/events/community/Qualchata.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAoABUB8JQBOgBuCTNJWAAD8YJyaeZ3R8Rj9iUtwb6Y8sisifv/V01t7T7xjWp4AAA==",
  "/images/events/community/food.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JYwCdADbpBV1AAD80OoPDAOOM61lX3sL7Ek8t0fICPkQ215fTI8AAAA=",
  "/images/events/community/group.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JQBOgBoeJGEyAADc+aS+eo1JKKLBbZHG1meWMuLHLWc0rr3BZX4wAAA=",
  "/images/events/community/jules.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoHAAoABUB8JZwAAp1426mDzAD+QBxwnCj1nJLK/5/L0qNQaCEIPnCoCsIAAA==",
  "/images/events/community/pator-tate.jpeg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAYABUB8JZACdAELMi0WIgAA/tT1MlxSOD1Rl7AWvAgZLl5k5PcgoKeRoZl2f1jm73XktLwAAA==",
  "/images/events/community/shamen.JPEG": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAoABUB8JZACdADbEGtwAMyBuxGMD60H068Ua/Q9Y9MkpAMe5y64np2ZPxsPnAA=",
  "/images/events/katrina/1.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAABwAQCdASoIAAoABUB8JYgCdAGIQAD+8CaNgMTv4eLEp6Uo4bNPMk2oGIxwAA==",
  "/images/events/katrina/2.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoIAAoABUB8JQBdgB8x4ewUFoAA841+3rtA5eLzrPO3y136ifBBoYH8c3j5WgzL4AA=",
  "/images/events/katrina/3.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAoABUB8JYgCdAEUpE84OgAA/p/WMIE0tT2qQPIPEv+o/VdqK7TBQEzFIAAA",
  "/images/events/katrina/4.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JYgCdAD0sk0aAAD+6PGgWWlG5Yvlp7NtKHl7NhK6AAAA",
  "/images/events/venue/art/Karen-1.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoKAAgABUB8JZACdAEOQcK+xEAA3kOjsuVXByNjrilB36iEnKSAaNh1fKcREgz5I5FfHGBNhuGyitz9iQAAAA==",
  "/images/events/venue/art/Karen-2.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoKAAgABUB8JbACdAEQK/p6AADeX9xJosNEx4RdWLZOzysrhtUVryf9OrQEIVBSfOlJyYavfBcfGtPIAAA=",
  "/images/events/venue/art/Karen-3.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JaACdADcCznAAPoK5r/sb/qi0jne53rISkKziEAKbI2FYGZMMAwAAAA=",
  "/images/events/venue/art/Karen-4.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAgABUB8JaACdADum36AAMwQQjrZkjAQY5yN9luw2kuE9880+eSgAAA=",
  "/images/events/venue/art/hero-2.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAcABUB8JagCdAEO10TLQADJbBf6XZtG8fjWMQAVwc9mLfhNFCFYOvj0iiAAAAA=",
  "/images/events/venue/art/hero.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAAgABUB8JagCdAD0Y3P4/5YA/Kdn59XWsNUV3GQ964OetxYtVl1W1wqf+2fMKVJ+rvNNuAA=",
  "/images/events/venue/church/church-1.jpg": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoHAAoABUB8JZgCdADz2mcAAADvKgrZU36nxvwqPSKJZd+AAAA=",
  "/images/events/venue/church/church-2.jpg": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoHAAoABUB8JagCdADz24NQ9qgA+nLKUH944u3JNFI8aJRtwNWmHyInw4AAAA==",
  "/images/events/venue/church/coffee-shop.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAcABUB8JYgCsADdlhEHgAD+kKkNro6Rnpmltd9bqCS/5er6lawJEaQjy1pjVtjtAAAA",
  "/images/events/venue/church/community.JPG": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JQBOgCIgSdm6AADc+/gZNMjCV1ObtO9/Ldzt3/K11kn+g9IC4hQAAAA=",
  "/images/events/venue/church/event-space-1.png": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoKAAcABUB8JbACdAEPDVEqGIAAywDlV9yLqgwtd1ZG/hriUUegGReo+UAAAA==",
  "/images/events/venue/church/event-space-2.png": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAcABUB8JbACdAD5djSEAADN5zydwA+t+6iE34t+AxAAzYIay4Tuxt2wfoyL1RSiAAAA",
  "/images/events/venue/church/outside-2.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAcABUB8JYgCdADZlgtAAP6g7IlrZ2T6BUzn84lta749WDrRzt93QGsNSQxARSHSrFAKFMsQxgAA",
  "/images/events/venue/church/outside5.jpeg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JaACdADcH5wiIAD0CrefGr80v4XpArZN5pu++fTlGvKqeDOvOBJAAAA=",
  "/images/events/venue/church/pator-tate.jpeg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAYABUB8JZACdAELMi0WIgAA/tT1MlxSOD1Rl7AWvAgZLl5k5PcgoKeRoZl2f1jm73XktLwAAA==",
  "/images/events/venue/co-work/Dedicated-desk.jpg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAcABUB8JZgCdADbVGHgAAD+Gc9rvDFwpsEu6IV403zGTxq4Ta43s5+AAAAA",
  "/images/events/venue/co-work/Networking.jpg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAcABUB8JbACdADcWG/3m8AA/o+1SEfn0kObvIhF8lpoITYkgfrt+2D4jGAvnMmHQpN1hAAAAA==",
  "/images/events/venue/co-work/Private-Office.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoKAAcABUB8JYwCdADdSHT9iZAAAPuEqpOP4wwn1SMUcCOwQMxCluVOp4eN/wX95HDFAAAA",
  "/images/events/venue/co-work/Studio-Empty.jpg": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoKAAcABUB8JbACdAEWPJ504WAA4hjSJDKsQPn9m9oOWiO2m9ItrOPnBqwsOkOgnXjNZOaOr7rVJS2Jv4AAAA==",
  "/images/events/venue/co-work/Studio-Full.jpg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoKAAcABUB8JbACdADdbGy0sAAA/PoDIHtwLirx/DnwwbQh+kTX8R/WulmWA0y4d3M5ujSs012S0/IboeSAAAAA",
  "/images/events/venue/co-work/Studio.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAcABUB8JYgCdAELWfRvDgAA+DOzgly2SZ18hEBPbiBdWWS99B1CfK5xROHtFY6sgAAA",
  "/images/events/venue/co-work/emty-desks.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAoABUB8JbACdADdcfR9wADgEx6lSdyYJHYkydvDHMxHccEG8TJczrYlDbLVg6NQAAAA",
  "/images/events/venue/co-work/private-w-person.jpg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAcABUB8JZQCdAELVSj1uQAA/ND2Hm49xm6GfYh7OYPifDBJxTOhzJeAGWm2AAA=",
  "/images/events/venue/concerts/1-Western-Wish.JPEG": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAgABUB8JYwCdADZnMAAAP4yshmTMOlpGGzGDPu7qqfAkC3AMGLcW8AAAA==",
  "/images/events/venue/concerts/2-PS.jpeg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoIAAoABUB8JZgCdAEOzD+iomAA/GgOjbDrGa/rkAzngLkKpgSHZVCzBCgrEdrBVTT3+AAA",
  "/images/events/venue/concerts/3-WW.JPEG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JQBOgCHcbvywAP1RmxKnQnxWQVcyGslAsolOUEYqOBAA",
  "/images/events/venue/concerts/4-PS.jpeg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAgABUB8JZACdADcrX27Y7gA/iUm0jQ1N1zOSZxi1JBOXiPK3p+80iBYkOuMkb959KUbZYDAAA==",
  "/images/events/venue/concerts/5-church.jpg": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoHAAoABUB8JZgCdADz2mcAAADvKgrZU36nxvwqPSKJZd+AAAA=",
  "/images/events/venue/concerts/6-lounge.png": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAAcABUB8JQBdgBuw51j1fAAA3ap8ktd/Xi+kPKsuomrgUdDhOem7ijfjAAAA",
  "/images/events/venue/concerts/7-outside.jpeg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JaACdADcH5wiIAD0CrefGr80v4XpArZN5pu++fTlGvKqeDOvOBJAAAA=",
  "/images/events/venue/dance/1.JPG": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JaACdAEWOncyIAD8iYBCYw+c4ZieDHcmswFLRy92KTa2aFpr8a+yJ9dgAA==",
  "/images/events/venue/dance/10.jpeg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JaACdADcH5wiIAD0CrefGr80v4XpArZN5pu++fTlGvKqeDOvOBJAAAA=",
  "/images/events/venue/dance/2.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JQBOgB6LM0bQYAD+qZuQp6FDE3YJrw1HlAaHCUUPqkoiAAA=",
  "/images/events/venue/dance/3.JPG": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAcABUB8JbACdAD8Jl5H3gAA/U63dnSy1e3qnvR1F4jflA8mGdcG9GeWHKN2b3rTm/ZZQDAgAA==",
  "/images/events/venue/dance/4.1.jpeg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoIAAoABUB8JZgCdAEOzD+iomAA/GgOjbDrGa/rkAzngLkKpgSHZVCzBCgrEdrBVTT3+AAA",
  "/images/events/venue/dance/4.jpg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoKAAcABUB8JbACdAEXe9AYTggA/j5Rm4GczSZ3h25ThRLzIfpENkNrra9XIULwOvpKiCY3t/xXebKNM4mHSuAA",
  "/images/events/venue/dance/5.JPG": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JbACdADcrXTNYgAA8OFO7CIvY4gJ8iTHogntnoTfrt7l2NaUJym6hcgAAA==",
  "/images/events/venue/dance/6.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAoABUB8JQBOgCMDHpaSnAD+vcEw00Qm8u3+PjU/VZWgzCVOXclZAAA=",
  "/images/events/venue/dance/7.png": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAAcABUB8JQBdgBuw51j1fAAA3ap8ktd/Xi+kPKsuomrgUdDhOem7ijfjAAAA",
  "/images/events/venue/dance/Event-1.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAoABUB8JQBOgCMDHpaSnAD+vcEw00Qm8u3+PjU/VZWgzCVOXclZAAA=",
  "/images/events/venue/dance/Event-2.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JQBOgB6LM0bQYAD+qZuQp6FDE3YJrw1HlAaHCUUPqkoiAAA=",
  "/images/events/venue/dance/Ricky.JPG": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAcABUB8JbACdAD8Jl5H3gAA/U63dnSy1e3qnvR1F4jflA8mGdcG9GeWHKN2b3rTm/ZZQDAgAA==",
  "/images/events/venue/martial-arts/1.JPG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoIAAoABUB8JQBOgBrjAAD8o5igjJZ+gPvIIlS3csQ5F5HiLwzJZAAA",
  "/images/events/venue/martial-arts/4.JPG": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAoABUB8JQBOgB5u9xAA99GyWtzB+ZUpB/Co6lM53yoAAAA=",
  "/images/events/venue/wedding/1-Aisle-Walk - Edited.jpg": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAcABUB8JaQAAv+4B2+wAAD6no3UAkyiS4S4YCACN/Zmiru3+AAA",
  "/images/events/venue/wedding/10-Celebration - Edited.jpg": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAYABUB8JQBOgCIBN8hdqAD0bagVB/+Tv7gGAuIdybqvn/GaVBbkgegAAA==",
  "/images/events/venue/wedding/12-Food.JPG": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoIAAoABUB8JYgCdAEWT64nz9cAAPo18Q3OBjPoSV/fzF4Pby4sKEbjVX5IXVzZVAziAAAA",
  "/images/events/venue/wedding/2-Pose.JPG": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoHAAoABUB8JYgCdAEO5RsAAAD+g+qkkmFQKIzZauOFjq/77gtR0xF0Tx7cwAAA",
  "/images/events/venue/wedding/3-outside-2.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAcABUB8JYgCdADZlgtAAP6g7IlrZ2T6BUzn84lta749WDrRzt93QGsNSQxARSHSrFAKFMsQxgAA",
  "/images/events/venue/wedding/4-church.jpg": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoHAAoABUB8JagCdADz24NQ9qgA+nLKUH944u3JNFI8aJRtwNWmHyInw4AAAA==",
  "/images/events/venue/wedding/5-Setup.JPG": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoGAAoABUB8JbACdAD0kotwAPEq0SFVbPN0rvi1Jp0NfjXkSRcAAA==",
  "/images/events/venue/wedding/6-church.jpg": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoHAAoABUB8JZgCdADz2mcAAADvKgrZU36nxvwqPSKJZd+AAAA=",
  "/images/events/venue/wedding/7-Wedding.jpg": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAgABUB8JaACdAELKXM4AAD6COLnNdBVVV1q9dGzFDsDzkEYeAaG/N63eGi/fOcoou2tgAA=",
  "/images/events/venue/wedding/8-Get-Ready.PNG": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoJAAoABUB8JaQAAvh6iq4sTAAA/rp9iAbXmeLu9VaiQii0gpzoVfnQ9IgAAAAA",
  "/images/events/venue/wedding/9-coffee-shop.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAcABUB8JYgCsADdlhEHgAD+kKkNro6Rnpmltd9bqCS/5er6lawJEaQjy1pjVtjtAAAA",
  "/images/events/venue/wedding/wedding-1.jpeg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JYgCdADZR/2AAPHMEO5yaYYiq+YBPF6GAuXihDXaBdpEIITnMPQA",
  "/images/events/venue/wedding/wedding-3.jpeg": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAcABUB8JQBOgCHHdnOAAPIvDf+fp6rmKBtcLRaiuoSSAXTO5jYfHi0AAA==",
  "/images/events/venue/wellness/1-breathwork-in-action.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JagCdADYC1QAAP7bYfDTp8ngUkjH2JpNpJw64bQ8jFDwWWNSN0AA",
  "/images/events/venue/wellness/10-outside.jpeg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JaACdADcH5wiIAD0CrefGr80v4XpArZN5pu++fTlGvKqeDOvOBJAAAA=",
  "/images/events/venue/wellness/2-event.png": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoHAAoABUB8JQBdgCHdrarBAADzjXuSpo+vsAP3fNRUMD7hH3+Izf4hwoe49k8+QAA=",
  "/images/events/venue/wellness/2.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAYABUB8JbACdADdlUxFwgAA4C1byeDj72Ca+VgwiOIzXy9cEGI4Oh0EHoRxO2y5AAAA",
  "/images/events/venue/wellness/3-yoga-class.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JZACsADg2fWAAP66e+2DL1EoFXzULvPJto4MnazkYQeDFxD07aITAAA=",
  "/images/events/venue/wellness/4-breathwork-class.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JaACdAD0FleZQAD+5STIVPCraTDuEKL1CHXIGUSKYlO8IRbY52HnnLAAAA==",
  "/images/events/venue/wellness/5-event-4.JPG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoHAAoABUB8JZACdAD0e3h38gAA+vPOnexYdg2AtAMRtc7E47mEAAAA",
  "/images/events/venue/wellness/6.JPEG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAgABUB8JZAAAlmU2hFCAAD+OwR5yD8JLcHCpk/l3Nwfvo1HwAAA",
  "/images/events/venue/wellness/7-mats.jpg": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAcABUB8JQBOgBuzaLwAAPA91UYSJp2UO+7+32bd5f7dAYAAAA==",
  "/images/events/venue/wellness/9-lounge.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAcABUB8JYgCsADdlhEHgAD+kKkNro6Rnpmltd9bqCS/5er6lawJEaQjy1pjVtjtAAAA",
  "/images/events/venue/wellness/Kristen-Boyle.png": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACQAQCdASoKAAYABUB8JaQAAluycmgA/t7sq8lPk6a2qeQWlLAAAA==",
  "/images/events/venue/wellness/Recenter (202).jpg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoHAAoABUB8JQBOgB5mCHYAANvG/wBJGodtpSiE5JmMTBS7WMf2v6WG0V2zuYyTwAA=",
  "/images/events/venue/wellness/Single Moms Thrive.JPEG": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAoABUB8JYwAAqvpWmAAAP7oUB3oyDseZzbS+cLva9dW3LMMac7tFr77sFnfgAA=",
  "/images/events/venue/wellness/breathwork-class.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JaACdAD0FleZQAD+5STIVPCraTDuEKL1CHXIGUSKYlO8IRbY52HnnLAAAA==",
  "/images/events/venue/wellness/breathwork-in-action.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JagCdADYC1QAAP7bYfDTp8ngUkjH2JpNpJw64bQ8jFDwWWNSN0AA",
  "/images/events/venue/wellness/shavasana.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JZQC7AD5h+mb7AD+3Z6PQKFBVtFn62sOeL5NBjyf+gAA",
  "/images/events/venue/wellness/yoga-class.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JZACsADg2fWAAP66e+2DL1EoFXzULvPJto4MnazkYQeDFxD07aITAAA=",
  "/images/hero/1.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAcABUB8JbACdADbFQN6AAD+huWcoXERUhzTDdoei6tFOBL+spJkGweoOBJMuEYwwyY5gAA=",
  "/images/hero/Cafe-East.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAgABUB8JZQCsAEWOrCYRkAA4iimHhyzzYAyjbmBG9fvBrxjg9cjwCRwTbeXvd7EAAAA",
  "/images/hero/Cafe-West.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoKAAgABUB8JQBOgBbszcsAAPJ15mU/PfChDkdttwY44efx8a0puYnlBYIQ6ryijZtnoTbcAAA=",
  "/images/hero/Glass-1.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAoABUB8JYwCdACvcyPUAPOnChScjpvRpNEeermbyHBSbQx7IaYkAAA=",
  "/images/hero/Glass-Group.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoKAAgABUB8JQBWACHh4iY2SQAA/nebIG8O4Sfdtmf+TXi0KbzKQ/zHr8AAAA==",
  "/images/hero/Lockers.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoKAAgABUB8JbACdADQ5sYmAPau9cnKFpbjUD52lC70XVuO3oiytM3cn/Vb215Ddr9zE+hs99mR12BXNIAAAA==",
  "/images/hero/Sound-Event2.JPG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoHAAoABUB8JZACdAD0e3h38gAA+vPOnexYdg2AtAMRtc7E47mEAAAA",
  "/images/hero/Sound-event.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoHAAoABUB8JQBOgCPw3/1X6AAA/qnJphrNoEYU1CCFz16cEEYZlcEAAAA=",
  "/images/hero/candles.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoHAAoABUB8JQBOgCHh0rg0FAAA/uzlIUPlQtOJE6g4CnTOWoAAAA==",
  "/images/hero/church-1.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAoABUB8JZgCdADbAMgAAO890cTcwhXlKcMBFX3sebL1OQbQAA==",
  "/images/hero/church-2.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoIAAoABUB8JagCdAEUU7T8jCQAAPpyvrUfejabmyR6ThtsLWFB9G3A1dea62ycgAA=",
  "/images/hero/church-3.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoIAAoABUB8JaACdADz2m57AAD57dz07At1tz7VUw2NegQEjOjfPxuk4UWZygAA",
  "/images/hero/logo.png": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4WAoAAAAQAAAACQAABAAAQUxQSC0AAAABYBgAQJls12zv/xs7IiI2AVS48bwpqi0uKkfGe/2vcS12BCxoZZ0BVz2UeA0AVlA4ICgAAABwAQCdASoKAAUABUB8JYwC7AFAAAD+5Epb/h/9g2f2cRbNndvQVmAA",
  "/images/hero/mat1.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAgABUB8JQBdgB6JEpfAAPzYTNOcnMQh4RTEK4GUVa1KEkAgGfuYnLh9LAAA",
  "/images/hero/mat2.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAcABUB8JQBOgBuzaJMAAPA91UYSJp8vWOb9VTiNkieS28AAAA==",
  "/images/hero/outside3.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAUABUB8JQBdgCFlKhIgAP4X+2Shy1378gMzB4GZWN3c+AAAAA==",
  "/images/hero/outside5.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JZgCdACkInH+AAD0C1JDWGkRK/RACtfZKHhcMU1Vjpl4BuIUpVcmgAA=",
  "/images/overlays/Circle.png": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSD0AAAABYBxJUps5A8j7r1cQyj82QQ4RMQEg1o21AHiyau+MYjMVBDfJQLU1lls/k5/yHFgyIL4KS4fPrQMIVSUAAFZQOCBCAAAAMAIAnQEqCgAKAAVAfCWoAsO2LQcgEVsgugAA/p/SEtmOdKi1RFYmravQxmtibC/MRCv9JYHuN8qnsV3/7xgc2EAA",
  "/images/overlays/Swirls.png": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoKAAoABUB8JZwABAAAAP7G2m4L6PXqOAA=",
  "/images/overlays/WaterColor.png": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSFEAAAABcBvbtqrs7/5xl4jQ3VK3DqAF6AJycjrQKrwsLyEiJoA/i/64ivCSGfWzNgICnfVyMwuCQGl3Oa+mPgTS2+d+0QsBWq07bxYU3pqOCCAIAq8AVlA4IDQAAACwAQCdASoKAAoABUB8JQBOgCFiyR5oAP7Y95D2EeRL1Cm3sFiK44eJYn7NX7NPEL8k4gAA",
  "/images/overlays/stained-glass.png": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4WAoAAAAQAAAACQAABQAAQUxQSBMAAAABD7AMERFBTJqw/qH9zBDR/8gBAFZQOCAmAAAAkAEAnQEqCgAGAAVAfCWkAAKdwVawAP7jVaL8Okixtykja9zgAAA=",
  "/images/pages/art-shows/art-show-tables.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAAgABUB8JaACdAD0Y3P4/5YA/Kdn59TWN34d3GQ964OetxYtVl1W1wqf+2fHGBg8UcEHIAA=",
  "/images/pages/art-shows/exhibition-stained-glass.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JaACdADcAqAAAPoK5r/scELATgWc73O9ZCUbsxuWhkZTwzbF2UAkgAA=",
  "/images/pages/art-shows/paintings-over-pews.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAgABUB8JbACdAEQDiwAAN5f3Emiw0THhF1YtnwfQ0OtUe6G7UDrdvObTwuGqdqTbYN3YS0I8AAA",
  "/images/pages/art-shows/partition-wall-paintings.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoKAAgABUB8JZACdAEOQcK+xEAA3kOjsuVXByNjrilB36iEnKSAaNh1fKcREgz5I5FfHGBNhuGyitz9iQAAAA==",
  "/images/pages/art-shows/vaulted-hall-exhibition.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JaACdAD1U8BYAMwQQjrWnvnMZ6IkNlCXjjXW+sxcqyAA",
  "/images/pages/art-shows/visitors-browsing.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAcABUB8JagCdAEO2b744ADMIGv8/KaucduAFm/MMN3WnFmEKycuQW5dAAAA",
  "/images/pages/classes/breathwork-class.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JagCdADYC1QAAP7bYfDTp8ngUkjH2JpNpJw64bQ8jFDwWWNSN0AA",
  "/images/pages/classes/circle-rollaway-mirror.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JbACdADdr1PuC+AA8OuzNG+6hhIj+x4aGBMJml4RFDJmLhteOCrJz24AAA==",
  "/images/pages/classes/dance-class-steps.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoKAAcABUB8JagCdADcqsczYAD9Trd8EjOp/BUyIQuyT3/vNXL8ShwVaY6FoTQapHzeGHyKinyuAAAA",
  "/images/pages/classes/dance-class-string-lights.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAcABUB8JaACdAEYGQbRjYAA/Ilulclk98Ef3QNNCcEbBx2jIEfx9bNC01+NfZDmkAAA",
  "/images/pages/classes/martial-arts-practice.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoIAAoABUB8JQBOgCPg/lTcZ3AA3ikOQz5+BIHqkaW9gsYy0AAAAA==",
  "/images/pages/classes/restorative-class.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAYABUB8JbACdADdlUxFwgAA4C1byeDj72Ca+VgwiOIzXy9cEGI4Oh0EHoRxO2y5AAAA",
  "/images/pages/classes/sound-bath-candlelight.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoIAAoABUB8JQBOgCPtyqwGGQAA/qjeBVzwNLp7owQxHAEwgjOT1gjAAAA=",
  "/images/pages/classes/sound-bath-gathering.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAoABUB8JYgCdAEUpE84OgAA/p/WMIE0tT2qQPIPEv+o/VdqK7TBQEzFIAAA",
  "/images/pages/classes/sound-bath-rose-window.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoIAAoABUB8JYgCdAEekvexdQYAAPrzzp3sgLM+qup9gTW/LSzyInTgAAA=",
  "/images/pages/concerts/acoustic-audience.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAkABUB8JQBOgB6V9jVwAAD+JvKzFjaXzVgWHzhCbbcnri4yE15wAAA=",
  "/images/pages/concerts/dance-floor-crowd.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAoABUB8JZgCdAEQC1fBEAD8aBa1UtOX1YsxGuccCAKLeZAjWgScNOqtm8xNAAitKIAA",
  "/images/pages/concerts/songwriters-round.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAgABUB8JQBOgB88yXAAAP4yshmTMKRTiR5T+MQwaOr4ad+DDYp7AAA=",
  "/images/pages/concerts/tango-starry-ceiling.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAgABUB8JQBOgB6RedH2oAD+qKBH+7tT+J+KoTTcIAoQPuPatAAA",
  "/images/pages/congregations/community-circle.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JQBOgBoeJGEyAADc+aS+eo1JKKLBbZHG1meWMuLHLWc0rr3BZX4wAAA=",
  "/images/pages/congregations/sunday-service.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAgABUB8JZACdAELZFRbtXAA/uAGLiL9lL324i7RfCHuO7kSac/lq0mVw70tvrbZwJNtMgAAAA==",
  "/images/pages/private-events/corporate-networking.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAcABUB8JbACdADZYgFSAAD+l5wuCIcqKsOCkl1rUGfb+sXZh1NT5YYhz75A3iaYHZjgAAA=",
  "/images/pages/studio/dedicated-desks.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAcABUB8JZgCdADbINC4AP4Zz2tvhNG/+668yqLMZEhLMJTrxPNC+oAAAA==",
  "/images/pages/studio/flex-studio.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAgABUB8JZACdAELMRu6wAD4V5ZqKnLwE/iH1qifdoI04taDvyfwkssmLf50WOPDPLmAAAA=",
  "/images/pages/studio/private-office.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAcABUB8JZQCdAELVSj5ykAA/ND2Hm49+OAi5TtGt/IsYZ8r/02GYVUuc9EAYAA=",
  "/images/pages/venue/cafe-lounge.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAgABUB8JZACdADhHKQoAP6RE3BFOx+LVV+7Nu1YLVg1wI9CL02fLH32KuzAk1LSrCjjdhU4AAAA",
  "/images/pages/venue/exterior-front.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAYABUB8JZgCdADbVGHsEAD0C1JDWGkRK/TomOPX4VCZtkTLah4HgG4hSlVyaAAAAA==",
  "/images/pages/venue/exterior-summer.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAgABUB8JYgCdADb61K4AAD+gpnT3xBeut/96gs1b++4LgvtV7Z24aooDjGRHx6FEZYhjAA=",
  "/images/pages/venue/full-coverage-mat.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAcABUB8JQBOgBuzaJMAAPA91UYSJgnBPEpnoD+PeOQBZRgAAA==",
  "/images/pages/venue/hall-projection-screen.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAoABUB8JYgCdACfjOAAAO89ny5j9IPa/8mtp8/vsc393zMAAA==",
  "/images/pages/venue/main-hall-rose-window-wide.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAYABUB8JZACdADdLkxT6AD1bat7TMIcAyDHzWAmiUHjLyzqLgAA",
  "/images/pages/venue/main-hall-rose-window.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAoABUB8JZgCdADbAMgAAO890cTcwhXlKcMBFX3sebL1OQbQAA==",
  "/images/pages/venue/og-venue.jpg": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoKAAUABUB8JZgCdAD0enHAAPuHeLzb9LJodJUUS+nVQTm7gAA=",
  "/images/pages/venue/seated-semicircle.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoKAAkABUB8JbACdADcq3xR4ADLM4gP7ooYxxlgDCBtgEhkGNw0T2qEQtXZaI0V7Hc4VvYRbKUQAA==",
  "/images/pages/venue/sunlit-hall-partition-wide.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoKAAYABUB8JYgCdAD5jiwdLoAA8hPahyEkyNn/Vvz+JPjIuvgGAAAA",
  "/images/pages/venue/sunlit-hall-partition.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoIAAoABUB8JaACdAEUU7T8jCQAAPpyvrUfejabmyR6ThtsLWFB9Cr/bPzyUAAA",
  "/images/pages/venue/sunlit-hall-wide.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAYABUB8JZACdAD5Zxh6AADyE9qnHduseyIlUbMpAT4zCs5cqyAA",
  "/images/pages/venue/sunlit-hall.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoIAAoABUB8JagCdAEUU7T8jCQAAPpyvrUfejabmyR6ThtsLWFB9G3A1dea62ycgAA=",
  "/images/pages/weddings/aisle-recessional.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAcABUB8JaQAAtzx2UQ5UAD6no3UAiqPQ6V+FSbnpUgjz0DAAAAA",
  "/images/pages/weddings/cake-table-couple.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoHAAoABUB8JZACdAEO9QBoAAD+g+qlLu6+wQhCkgnujCmcVxNb4c6C1q2Tv1gAAAA=",
  "/images/pages/weddings/celebration-kiss.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAYABUB8JQBOgCKdQrwBsAD0U/n0i/bF6WjEYFENEHkDpbjba27UeFQAAA==",
  "/images/pages/weddings/ceremony-arch-side.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoKAAcABUB8JYgCdACCSE4AAPHiu67I3iL4F/RlQXsBZxtYX4SdbaQGqU0xEUjDRnZOwwAA",
  "/images/pages/weddings/ceremony-arch.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JQBOgCIBJSqAAPIvRBRWe1z69Pngq2EFTmezPCoQYkhEDEptgAAA",
  "/images/pages/weddings/getting-ready.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoJAAoABUB8JaQAAt0K/5Z8AAD+zGPSZIyHvANcqtsOw1l8MhzadRHJUyKAAAAA",
  "/images/pages/weddings/head-table-cake.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoGAAoABUB8JbACdADyVagAAPEDKcflGulac978/wZJMm/ZZRS9TFgAAAA=",
  "/images/pages/weddings/og-weddings.jpg": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAUABUB8JQBOgCKKHyLIAPshF+FJ29S+SoB37TjikMCosqAXT6fAAAA="
};

export function getBlurDataURL(src: string): string | undefined {
  return blurDataMap[src];
}
