// Auto-generated blur placeholders for images
// Run: node scripts/generate-blur-placeholders.js

export const blurDataMap: Record<string, string> = {
  "/images/events/2.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAYABUB8JbACdADdlUxFwgAA4C1byeDj72Ca+VgwiOIzXy9cEGI4Oh0EHoRxO2y5AAAA",
  "/images/events/art/Karen-1.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoKAAgABUB8JZACdAEOQcK+xEAA3kOjsuVXByNjrilB36iEnKSAaNh1fKcREgz5I5FfHGBNhuGyitz9iQAAAA==",
  "/images/events/art/Karen-2.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoKAAgABUB8JbACdAEQK/p6AADeX9xJosNEx4RdWLZOzysrhtUVryf9OrQEIVBSfOlJyYavfBcfGtPIAAA=",
  "/images/events/art/Karen-3.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JaACdADcCznAAPoK5r/sb/qi0jne53rISkKziEAKbI2FYGZMMAwAAAA=",
  "/images/events/art/Karen-4.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAgABUB8JaACdADum36AAMwQQjrZkjAQY5yN9luw2kuE9880+eSgAAA=",
  "/images/events/art/hero-2.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAcABUB8JagCdAEO10TLQADJbBf6XZtG8fjWMQAVwc9mLfhNFCFYOvj0iiAAAAA=",
  "/images/events/art/hero.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAAgABUB8JagCdAD0Y3P4/5YA/Kdn59XWsNUV3GQ964OetxYtVl1W1wqf+2fMKVJ+rvNNuAA=",
  "/images/events/community/Qualchata.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAoABUB8JQBOgBuCTNJWAAD8YJyaeZ3R8Rj9iUtwb6Y8sisifv/V01t7T7xjWp4AAA==",
  "/images/events/community/Terri-Event.JPG": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoHAAoABUB8JYgC7AEOZk4JygAA4Bk0axIXlGZUB7qiN13QwN0R8WvNCvxfgAAA",
  "/images/events/community/breathwork.webp": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoIAAoABUB8JYwAAuYa/9bYAPKPyEGfS5U4Do05wPGIcUAA",
  "/images/events/community/food.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JYwCdADbpBV1AAD80OoPDAOOM61lX3sL7Ek8t0fICPkQ215fTI8AAAA=",
  "/images/events/community/gala.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JYwCdAELXTlCkAD+6fKAMnzI/wsAkvLAvgBSx0HEfYgA",
  "/images/events/community/group.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JQBOgBoeJGEyAADc+aS+eo1JKKLBbZHG1meWMuLHLWc0rr3BZX4wAAA=",
  "/images/events/community/jules.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoHAAoABUB8JZwAAp1426mDzAD+QBxwnCj1nJLK/5/L0qNQaCEIPnCoCsIAAA==",
  "/images/events/community/tantra.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoKAAoABUB8JbACdADZYq0AAOAmvMl9xgW97aDFfXXmu53EnC+SxoEuIacbaDiIqzBwWXOEoBapw5sAAAA=",
  "/images/events/dance/Event-1.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAoABUB8JQBOgCMDHpaSnAD+vcEw00Qm8u3+PjU/VZWgzCVOXclZAAA=",
  "/images/events/dance/Event-2.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JQBOgB6LM0bQYAD+qZuQp6FDE3YJrw1HlAaHCUUPqkoiAAA=",
  "/images/events/dance/Event.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAoABUB8JaACdAEfaSyoAAD+va7rp6770DxQTAlrv+rJ/HHg5kvWiyKDLbZ5AAA=",
  "/images/events/dance/MHQ.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAoABUB8JbACdADyUhuAAOjwCdeZWoMATQN1MJgFw8FJuO0trt5HYfIN1kaWAAA=",
  "/images/events/dance/kids.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoJAAoABUB8JbACdADZYwDkAAD+x2+BAMIFKR23bfjwvq5XZXeHfaHAJQDLuxwdgu20C/Uj1W4FEAAA",
  "/images/events/dance/teaching.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAYABUB8JagCdAD5dj8A5IAA+p6YwntZ8zvosx/4IEZbEvcB9oyZVDoIPQLBgAA=",
  "/images/events/judo/1.JPG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoIAAoABUB8JQBOgBrjAAD8o5igjJZ+gPvIIlS3csQ5F5HiLwzJZAAA",
  "/images/events/judo/4.JPG": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAoABUB8JQBOgB5u9xAA99GyWtzB+ZUpB/Co6lM53yoAAAA=",
  "/images/events/katrina/1.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAABwAQCdASoIAAoABUB8JYgCdAGIQAD+8CaNgMTv4eLEp6Uo4bNPMk2oGIxwAA==",
  "/images/events/katrina/2.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoIAAoABUB8JQBdgB8x4ewUFoAA841+3rtA5eLzrPO3y136ifBBoYH8c3j5WgzL4AA=",
  "/images/events/katrina/3.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAoABUB8JYgCdAEUpE84OgAA/p/WMIE0tT2qQPIPEv+o/VdqK7TBQEzFIAAA",
  "/images/events/katrina/4.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JYgCdAD0sk0aAAD+6PGgWWlG5Yvlp7NtKHl7NhK6AAAA",
  "/images/events/yoga/breathwork-class.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JaACdAD0FleZQAD+5STIVPCraTDuEKL1CHXIGUSKYlO8IRbY52HnnLAAAA==",
  "/images/events/yoga/breathwork-in-action.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAAcABUB8JagCdADYC1QAAP7bYfDTp8ngUkjH2JpNpJw64bQ8jFDwWWNSN0AA",
  "/images/events/yoga/shavasana.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAoABUB8JZQC7AD5h+mb7AD+3Z6PQKFBVtFn62sOeL5NBjyf+gAA",
  "/images/events/yoga/yoga-class.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JZACsADg2fWAAP66e+2DL1EoFXzULvPJto4MnazkYQeDFxD07aITAAA=",
  "/images/hero/1.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAcABUB8JbACdADbFQN6AAD+huWcoXERUhzTDdoei6tFOBL+spJkGweoOBJMuEYwwyY5gAA=",
  "/images/hero/Cafe-East.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoKAAgABUB8JZQCsAEWOxzZ1YYAAOIoph4cq0rJ2slLuNK3/aKBKWE0m+P0XIlzSauAAA==",
  "/images/hero/Cafe-West.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoKAAgABUB8JQBOgBbszcsAAPJ15mU/PfChDkdttwY44efx8a0puYnlBYIQ6ryijZswEbAHgAA=",
  "/images/hero/Glass-1.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAoABUB8JYwCdACvcyPUAPOnChScjpvRpNEeermbyHBSbQx7F7qgAAA=",
  "/images/hero/Glass-Group.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAgABUB8JQBOgCHh4E5bUAD+d5sgbtKHUOUq5LJpNU/EgBNLDW5mBVgAAA==",
  "/images/hero/Lockers.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoKAAgABUB8JbACdADQ5rReAAD2rvXJyhaW41A+dpQu9F1bjt6A0/u3cn/Vb2N5+SCOAM7sOfG6yL1HygAAAA==",
  "/images/hero/Sound-Event2.JPG": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoHAAoABUB8JZACdAD0e3h38gAA+vPOnexYdg2AtAMRtc7E47mEAAAA",
  "/images/hero/Sound-event.JPG": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoHAAoABUB8JQBOgCPw3/1X6AAA/qnJphrNoEYU1CCFz16cEEYZlcEAAAA=",
  "/images/hero/candles.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAQCdASoHAAoABUB8JQBOgCHh0rg0FAAA/uzlIUPlQtOJE6g4CnJaAAA=",
  "/images/hero/church-1.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAoABUB8JZgCdADbAQAAAO89lzkPhbiom/Bl13Ohxl9KDMAAAA==",
  "/images/hero/church-2.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoIAAoABUB8JagCdAEUUpaZAAD6cr61H3kNuPECWoC9aMNW45fUTizSy+RE+HAA",
  "/images/hero/church-3.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAoABUB8JaACdAD0oYEgCAAA+favy3EGq1RUPhM28aN7gTjIzDjYO6u1ugAA",
  "/images/hero/logo.png": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4WAoAAAAQAAAACQAABAAAQUxQSC0AAAABYBgAQJls12zv/xs7IiI2AVS48bwpqi0uKkfGe/2vcS12BCxoZZ0BVz2UeA0AVlA4ICgAAABwAQCdASoKAAUABUB8JYwC7AFAAAD+5Epb/h/9g2f2cRbNndvQVmAA",
  "/images/hero/mat1.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAgABUB8JQBOgB6JG4uDQAD82EzTnJzEIeEUxCuBlFWtShJAIBn8A7osm3AA",
  "/images/hero/mat2.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAcABUB8JQBOgBuzaJMAAPA91UYSJgnBPEpnoD+PeOQBZRgAAA==",
  "/images/hero/outside3.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAUABUB8JQBdgCFlKhIgAP4X+2Shy1378gMzB4GZWN3c+AAAAA==",
  "/images/hero/outside5.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAYABUB8JZgCdACkInH+AAD0C1JDWGkRK/RACtfZKHhcMU1Vjpl4BuIUpVcmgAA=",
  "/images/overlays/Circle.png": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSD0AAAABYBxJUps5A8j7r1cQyj82QQ4RMQEg1o21AHiyau+MYjMVBDfJQLU1lls/k5/yHFgyIL4KS4fPrQMIVSUAAFZQOCBCAAAAMAIAnQEqCgAKAAVAfCWoAsO2LQcgEVsgugAA/p/SEtmOdKi1RFYmravQxmtibC/MRCv9JYHuN8qnsV3/7xgc2EAA",
  "/images/overlays/Swirls.png": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoKAAoABUB8JZwABAAAAP7G2m4L6PXqOAA=",
  "/images/overlays/WaterColor.png": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSFEAAAABcBvbtqrs7/5xl4jQ3VK3DqAF6AJycjrQKrwsLyEiJoA/i/64ivCSGfWzNgICnfVyMwuCQGl3Oa+mPgTS2+d+0QsBWq07bxYU3pqOCCAIAq8AVlA4IDQAAACwAQCdASoKAAoABUB8JQBOgCFiyR5oAP7Y95D2EeRL1Cm3sFiK44eJYn7NX7NPEL8k4gAA",
  "/images/overlays/stained-glass.png": "data:image/webp;base64,UklGRngAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSCQAAAABHyAkIDGiiAg2KGokSdkX+xexKxIPNET0fwLg6oFZ9uGBcAVWUDggLgAAADABAJ0BKgoACgAFQHwlpAADcAD+7zX//lwFXh2yIQDQGcyA7A0U6BkC2rcAAAA="
};

export function getBlurDataURL(src: string): string | undefined {
  return blurDataMap[src];
}
